//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillasBonaterra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        public System.Guid id_acceso { get; set; }
        public System.Guid id_asunto { get; set; }
        public System.Guid id_visitante { get; set; }
        public System.Guid id_domicilio { get; set; }
        public System.DateTime fecha { get; set; }
        public string placa { get; set; }
        public string identificacion { get; set; }
        public string cono { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
    
        public virtual Asuntos Asuntos { get; set; }
        public virtual Domicilios Domicilios { get; set; }
        public virtual Visitantes Visitantes { get; set; }
    }
}
