//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillasBonaterra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicilios()
        {
            this.Accesos = new HashSet<Accesos>();
            this.TarjetasAcceso = new HashSet<TarjetasAcceso>();
        }
    
        public System.Guid id_domicilio { get; set; }
        public System.Guid id_calle { get; set; }
        public System.Guid id_usuario { get; set; }
        public string no_casa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesos> Accesos { get; set; }
        public virtual Calles Calles { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarjetasAcceso> TarjetasAcceso { get; set; }
    }
}
