//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillasBonaterra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Villas_BonaterraEntities : DbContext
    {
        public Villas_BonaterraEntities()
            : base("name=Villas_BonaterraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesos> Accesos { get; set; }
        public virtual DbSet<Asuntos> Asuntos { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<Calles> Calles { get; set; }
        public virtual DbSet<Domicilios> Domicilios { get; set; }
        public virtual DbSet<RecoveryPassword> RecoveryPassword { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TarjetasAcceso> TarjetasAcceso { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuariosRoles> UsuariosRoles { get; set; }
        public virtual DbSet<VerificacionVisitantes> VerificacionVisitantes { get; set; }
        public virtual DbSet<Visitantes> Visitantes { get; set; }
    }
}
