//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VillasBonaterra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveryPassword
    {
        public System.Guid Id { get; set; }
        public System.Guid IdUser { get; set; }
        public System.Guid Code { get; set; }
        public System.DateTime Date { get; set; }
        public bool Used { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
